CREATE TABLE resorts (
    id INT PRIMARY KEY,
    location_id INT,
    region_code TEXT,
    country_code TEXT,
    area_name TEXT,
    name TEXT,
    description TEXT,
    entity TEXT,
    minivac TEXT,
    state TEXT,
    country TEXT,
    discovery TEXT,
    iris_id INT,
    exotic bool,
    type TEXT,
    check_in_time TEXT,
    check_out_time TEXT,
    resort_url_code TEXT,
    addresses JSONB,
    phones JSONB,
    allowed_program_tiers JSONB,
    club_ids JSONB,
    region_ids JSONB
);
